import Link from 'next/link';

import { componentDocs } from '@/lib/component-docs';
import { components } from '@/lib/generated/components';
import { componentPreviews } from '../../../../components/component-previews';
import { isLocale, type Locale, withLocale } from '@/lib/i18n';
import { buildAlternates } from '@/lib/seo';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale: rawLocale } = await params;
  const locale: Locale = isLocale(rawLocale) ? rawLocale : 'en';
  return { alternates: buildAlternates('/components', locale) };
}

export default async function ComponentsIndexPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale: rawLocale } = await params;
  const locale: Locale = isLocale(rawLocale) ? rawLocale : 'en';

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-fleet-h2Strong">
          {locale === 'ko' ? '컴포넌트 개요' : 'Components Overview'}
        </h1>
        <p className="mt-2 text-fleet-body3 text-muted-foreground">
          {locale === 'ko' ? (
            <>
              이 목록은 <code className="font-mono">packages/components/src</code>를 스캔해 자동
              생성됩니다.
            </>
          ) : (
            <>
              This list is generated by scanning <code className="font-mono">packages/components/src</code>.
            </>
          )}
        </p>
      </div>

      <div className="flex flex-wrap gap-6">
        {components.map((c) => {
          const Preview = componentPreviews[c.slug];

          return (
            <Link
              key={c.slug}
              href={withLocale(`/components/${c.slug}`, locale)}
              className="group relative overflow-hidden rounded-2xl bg-card px-4 py-6 transition-all hover:border-primary shadow-sm no-underline"
            >
              <div className="flex aspect-video w-full items-center justify-center overflow-hidden rounded-lg text-muted-foreground transition-colors group-hover:bg-primary/5 group-hover:text-primary h-48 lg:h-64 lg:w-64">
                {Preview ? (
                  Preview
                ) : (
                  <div className="flex h-full w-full items-center justify-center p-4">
                    <div className="h-10 w-full rounded border bg-background/50" />
                  </div>
                )}
              </div>
              <div className="flex items-center justify-between gap-3 pt-4">
                <div className="text-fleet-body2 text-muted-foreground">{c.name}</div>
                
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
}

