import fs from 'node:fs';
import path from 'node:path';

type GeneratedComponent = {
  name: string;
  slug: string;
};

function toSlug(name: string): string {
  // "OTPInput" -> "otp-input", "IconButton" -> "icon-button", "TabBar" -> "tab-bar"
  // 1) Separate transitions like "aB" -> "a-B"
  // 2) Separate acronym transitions like "OTPI" + "nput" -> "OTP-Input"
  const withDashes = name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2');
  return withDashes.toLowerCase();
}

function isDir(p: string) {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}

function main() {
  const docsRoot = path.resolve(__dirname, '..'); // docs/
  const monorepoRoot = path.resolve(docsRoot, '..'); // repo root
  const componentsSrc = path.join(monorepoRoot, 'packages/components/src');
  const playgroundComponentsDir = path.join(
    monorepoRoot,
    'apps/playground/app/components',
  );
  const outFile = path.join(docsRoot, 'lib/generated/components.ts');

  const entries = fs.readdirSync(componentsSrc, { withFileTypes: true });
  const folders = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((name) => name !== '__tests__');

  const components: GeneratedComponent[] = folders
    .filter((name) => isDir(path.join(componentsSrc, name)))
    .map((name) => {
      const base = toSlug(name);
      const candidates = Array.from(
        new Set([base, base.replace(/-/g, ''), name.toLowerCase()]),
      );
      const matched =
        candidates.find((c) =>
          fs.existsSync(path.join(playgroundComponentsDir, `${c}.tsx`)),
        ) ?? base;
      return { name, slug: matched };
    })
    .sort((a, b) => a.slug.localeCompare(b.slug));

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(
    outFile,
    [
      '/* eslint-disable */',
      '// This file is generated by scripts/generate-components-index.ts',
      '',
      `export const components = ${JSON.stringify(components, null, 2)} as const;`,
      '',
      'export type ComponentItem = (typeof components)[number];',
      'export type ComponentSlug = ComponentItem["slug"];',
      '',
    ].join('\n'),
    'utf8',
  );

  console.log(`[docs] generated: ${outFile}`);
}

main();

