import fs from 'node:fs';
import path from 'node:path';

type ComponentItem = { name: string; slug: string };

function main() {
  const docsRoot = path.resolve(__dirname, '..');
  const componentsFile = path.join(docsRoot, 'lib/generated/components.ts');
  const contentDirKo = path.join(docsRoot, 'content/ko/components');
  const contentDirEn = path.join(docsRoot, 'content/en/components');
  const outMapKo = path.join(docsRoot, 'lib/generated/component-content.ko.ts');
  const outMapEn = path.join(docsRoot, 'lib/generated/component-content.en.ts');

  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { components } = require(componentsFile) as { components: ComponentItem[] };

  fs.mkdirSync(contentDirKo, { recursive: true });
  fs.mkdirSync(contentDirEn, { recursive: true });

  const placeholderMarker = '> TODO: 문서를 작성해 주세요.';

  for (const c of components) {
    const fileKo = path.join(contentDirKo, `${c.slug}.mdx`);
    const fileEn = path.join(contentDirEn, `${c.slug}.mdx`);
    const body =
      `> TODO: 문서를 작성해 주세요.\n\n` +
      `## 한줄 요약\n\nTODO\n\n` +
      `## 사용법\n\nTODO\n\n` +
      `## 접근성\n\nTODO\n\n` +
      `## Props\n\nTODO (다음 세션에서 표 전략 확정)\n`;

    if (!fs.existsSync(fileKo)) {
      fs.writeFileSync(fileKo, body, 'utf8');
      console.log(`[docs] created: ${path.relative(docsRoot, fileKo)}`);
    }

    // 기존 자동 생성 스켈레톤(# Title 포함)을 새 형식으로 마이그레이션(사용자가 직접 편집한 파일은 건드리지 않음)
    const existing = fs.readFileSync(fileKo, 'utf8');
    const expectedOldHeader = `# ${c.name}\n\n${placeholderMarker}`;
    if (existing.startsWith(expectedOldHeader)) {
      fs.writeFileSync(fileKo, body, 'utf8');
      console.log(`[docs] migrated: ${path.relative(docsRoot, fileKo)}`);
    }

    // NOTE: en은 기본적으로 "없으면 fallback"을 허용한다.
    // 필요 시 번역 워크플로우에 맞춰 placeholder 자동 생성을 켤 수 있다.
    if (process.env.DOCS_CREATE_EN_PLACEHOLDERS === '1' && !fs.existsSync(fileEn)) {
      const enBody =
        `> TODO: Please write docs.\n\n` +
        `## One-liner\n\nTODO\n\n` +
        `## Usage\n\nTODO\n\n` +
        `## Accessibility\n\nTODO\n\n` +
        `## Props\n\nTODO\n`;
      fs.writeFileSync(fileEn, enBody, 'utf8');
      console.log(`[docs] created: ${path.relative(docsRoot, fileEn)}`);
    }
  }

  // Generate import maps for Next (static analyzable).
  function generateMap(outFile: string, locale: 'ko' | 'en') {
  const lines: string[] = [];
  lines.push('/* eslint-disable */');
  lines.push('// This file is generated by scripts/generate-component-content.ts');
  lines.push('');
  lines.push(
    'export const componentContent: Record<string, () => Promise<{ default: React.ComponentType<any> }>> = {',
  );

  for (const c of components) {
      const rel = `../../content/${locale}/components/${c.slug}.mdx`;
      const absolute = path.join(docsRoot, 'content', locale, 'components', `${c.slug}.mdx`);
      if (locale === 'en' && !fs.existsSync(absolute)) continue;
    lines.push(`  ${JSON.stringify(c.slug)}: () => import(${JSON.stringify(rel)}),`);
  }
  lines.push('} as const;');
  lines.push('');

    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, lines.join('\n'), 'utf8');
    console.log(`[docs] generated: ${path.relative(docsRoot, outFile)}`);
  }

  generateMap(outMapKo, 'ko');
  generateMap(outMapEn, 'en');
}

main();

